name: update_hell
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.26.0
  - python=3.10.13
  - pip=23.3
  - pip:
      - category-encoders==2.6.2
      - deepchecks==0.17.5
      - importlib-metadata==6.8.0
      - ipython==7.34.0
      - lightgbm==4.1.0
      - matplotlib==3.8.0
      - mlflow==2.7.1
      - mlxtend==0.23.0
      - numpy==1.26.1
      - pandas==2.1.1
      - pre-commit==3.5.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
